### ISSUE TITLE
Publish to NuGet

### ISSUE THREAD

**Issue by paulirwin** [zzzprojects/EntityFramework6-DotNetStandard#3]

**Comment by hirre** [comment]
https://github.com/zzzprojects/EntityFramework-Plus/issues/329

Now we need them to sync with this project :)

**Comment by troylutton** [comment]
A NuGet package would be fantastic.  Thanks for your hard work @paulirwin and look forward having the opportunity to keep using entity framework 6 in my .Net Core applications.

**Comment by cunnpole** [comment]
As someone who is currently fighting a loosing battle trying to move from vs2015 to 2017 with EF6.2, a nuget package of this would be very handy. Apparently the add-migrations/update-database commands within visual studio gets very confused if you use model annotations such as Required and have .Net Standard 2.0 dependencies (it picks up the wrong version of ComponentModel). Fluent works but I have hundreds of entities to I haven't got time to change for no good reason. Automigrations and Migrate.exe work also. This package looks like it might work around the problem entirely.

**Comment by patrikwlund** [comment]
@cunnpole Microsoft just announced their plans for .NET Core 3, which includes support for EF6 on .NET Core. See the blog post here: https://blogs.msdn.microsoft.com/dotnet/2018/05/07/net-core-3-and-support-for-windows-desktop-applications/

Timeframe (from link above):
> We are planning on releasing a first preview of .NET Core 3 later this year and the final version in 2019

These news pretty much deprecate this project, with the only downside being that .NET Core 3 is probably a year away. Because of this it is unlikely that I personally put much more time into this project. It works, but is missing tooling for migrations, which is a requirement if you don't want to use a combination of the original EF6 and this project. Doesn't make for a good nuget package. Then there's also the legal matter of publishing an unofficial EF6 fork on NuGet.

I would suggest either waiting for .NET Core 3 or building this fork yourself. Be aware that I don't run this in production myself, and wouldn't recommend it without rigorous testing.

**Comment by paulirwin** [comment]
@patrikwlund While interesting, that doesn't change the mission of this fork. I have a fairly large application on EF6 that I need to get to .NET Core this _quarter_, not in 2019. And there are many people out there, myself included, that do not need migrations because we use the (IMO way better) SQL Server Database Projects deployment approach instead. Even without migrations tooling, this NuGet package will still have tremendous value. And as long as we keep the license in place and make it clear this is not a Microsoft-supported package, I don't see any legal issues with publishing this fork.

I was having an issue with the new MSBuild project format of how to specify a dependency on the main EntityFramework project from EntityFramework.SqlServer. If someone can help with that I can get it published soon.

**Comment by JonathanMagnan** [comment]
Hello all,

We will close this issue as EF Classic should now be used instead: https://entityframework-classic.net/

Nuget are already available:
- Community version (free): https://www.nuget.org/packages/Z.EntityFramework.Classic.Community
- Enterprise version: https://www.nuget.org/packages/Z.EntityFramework.Classic/

Best Regards,

Jonathan
